from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp') + Glob('./board_config/*.c')
CPPPATH = [cwd, os.path.join(cwd, "board_config")]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
